### ISSUE TITLE
Please share your code

### ISSUE THREAD

**Issue by Tea7374** [grip-unina/poi-forensics#1]
I've been waiting for this code for a long time.plz

**Comment by wang-qichang** [comment]
Me too

**Comment by chunguangqu** [comment]
me too

**Comment by lzhyu** [comment]
Hi, I've implemented an unofficial version [here](https://github.com/lzhyu/poi-forensics-unofficial). Maybe you can borrow some code.

**Comment by Tea7374** [comment]
> Hi, I've implemented an unofficial version [here](https://github.com/lzhyu/poi-forensics-unofficial). Maybe you can borrow some code.

thank you

**Comment by petros94** [comment]
Any news on the code release?

**Comment by raining-dev** [comment]
Any news on the code release?

**Comment by davin11** [comment]
the test code is at https://github.com/grip-unina/poi-forensics/tree/main/app_code
