### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by YasamanAdl94** [grip-unina/poi-forensics#3]
Hello,

Will the training code be provided for reproduction purposes? Thank you.

**Comment by Wertiz** [comment]
As of now, we are not planning to release the training code. In case you would like to replicate our training approach, all the information can be found in the [paper](https://openaccess.thecvf.com/content/CVPR2023W/WMF/papers/Cozzolino_Audio-Visual_Person-of-Interest_DeepFake_Detection_CVPRW_2023_paper.pdf). In case you have more specific questions, feel free to open a new issue.
