### ISSUE TITLE
code error :is pois not poi

### ISSUE THREAD

**Issue by ats4869** [grip-unina/poi-forensics#4]
![image](https://github.com/grip-unina/poi-forensics/assets/75195557/4b1433d1-e941-4868-8a81-b9f46df947fb)

**Comment by ats4869** [comment]
dir_poi is error.it should be pois not poi

**Comment by Wertiz** [comment]
Thank you, fixed in commit [8f6864f](https://github.com/grip-unina/poi-forensics/commit/8f6864f918da6dc0dd827b76ba533aae469da35e)
