### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by mamarasulovs** [grip-unina/poi-forensics#6]
I'm working on reproducing your results for research purposes, and having access to your code would be a huge help. If it turns out you can't share the actual code, would it be possible to release a simplified or redacted version?

Feel free to reach out to me directly at mamarasulovsardor@gmail.com

Thanks again

**Comment by Wertiz** [comment]
Thank you for your interest in our work!
 As we are still working on this project, the training code cannot be shared yet. Once finished, we will release the final version.
